#!/bin/bash
# kill -9 `ps | grep bash | grep -v 'whitebox' | grep -v 'clean' | grep -v 'trun' | awk '{ printf "%s ", $1 }'`
cleanfifos
if [ "1" == `cat ../copy.txt` ]
then
    rm -rf ../_posts/*
    ./makenew
fi
