#!/bin/bash
kill -9 `ps | grep bash | grep -v 'whitebox' | grep -v 'clean' | grep -v 'trun' | awk '{ printf "%s ", $1 }'`
rm -f wire_*
rm -f pin_*
rm -rf ../_posts/*
if [ "1" == `cat debug.txt` ]
then
    ./makenew
fi
