#!/bin/bash
filename=pin_$RANDOM
content=pin_$RANDOM
#find ../_new -iname "*" | while read targetMaybeWithBlanks
for targetMaybeWithBlanks in `ls -1b ../_new`
do
    target=`echo "${targetMaybeWithBlanks}" | sed -e 's/ /\\ /g'`
    echo "creating post from [${target}]"
    rm -f pin_*
    mkfifo ${filename}
    mkfifo ${content}
    ./scrivener-to-jekyll 3<"${filename}" 4<"${content}" &
    echo "${target}" >"${filename}" &
    echo "don't care" >"${content}" &
done

