#!/bin/bash
./debug-entry $0
./makenew

filename=pin_$RANDOM
content=pin_$RANDOM
mkfifo ${filename}
mkfifo ${content}

target=../_new/test.html

./scrivener-to-jekyll 3<${filename} 4<${content} &

echo ${target} >${filename} &
echo "don't care" >${content} &

./debug-exit $0
